# A workaround to resolve Local Zeebe Gateway domain within the cluster
# which is needed for WebModeler to access Local Zeebe Gateway domain over TLS.
# Ref: https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        rewrite name substring zeebe.local.distro.ultrawombat.com ingress-nginx-controller.ingress-nginx.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
