global:
  identity:
    auth:
      enabled: true
      publicIssuerUrl: "https://local.distro.ultrawombat.com/auth/realms/camunda-platform"
      operate:
        redirectUrl: "https://local.distro.ultrawombat.com/operate"
      tasklist:
        redirectUrl: "https://local.distro.ultrawombat.com/tasklist"
      optimize:
        redirectUrl: "https://local.distro.ultrawombat.com/optimize"
      console:
        redirectUrl: "https://local.distro.ultrawombat.com"
      webModeler:
        redirectUrl: "https://local.distro.ultrawombat.com/modeler"
  ingress:
    enabled: true
    className: ""
    host: "local.distro.ultrawombat.com"
    tls:
      enabled: true
      secretName: camunda-platform
# console
console:
  enabled: true
  contextPath: "/"
  image:
    tag: SNAPSHOT
    pullSecrets:
      - name: registry-camunda-cloud
connectors:
  enabled: true
  inbound:
    mode: disabled
# Configure elastic search to make it running for local development
elasticsearch:
  # Request a single node with a persistent volume
  master:
    replicaCount: 1
    persistence:
      size: 15Gi
identity:
  enabled: true
  contextPath: "/identity"
  fullURL: "https://local.distro.ultrawombat.com/identity"
  image:
    tag: SNAPSHOT
operate:
  enabled: true
  contextPath: "/operate"
  image:
    tag: SNAPSHOT
optimize:
  enabled: true
  contextPath: "/optimize"
  image:
    tag: SNAPSHOT
tasklist:
  enabled: true
  contextPath: "/tasklist"
  image:
    tag: SNAPSHOT
# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  image:
    tag: 8.5.0-RC2
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi
zeebe-gateway:
  image:
    tag: 8.5.0-RC2
  replicas: 1
  ingress:
    enabled: true
    className: ""
    host: "zeebe.local.distro.ultrawombat.com"
    tls:
      enabled: true
      secretName: camunda-platform
webModeler:
  contextPath: "/modeler"
  enabled: true
  image:
    tag: 8.5.0-alpha2
    pullSecrets:
      - name: registry-camunda-cloud
  restapi:
    mail:
      smtpHost: smtp.example.com
      smtpPort: 587
      smtpUser: user
      smtpPassword: secret
      # email address to be displayed as sender of emails from Web Modeler
      fromAddress: no-reply@example.com
postgresql:
  enabled: true
