#!/bin/bash

# setup

COMMAND=$1
CONSOLE=$2

log() {
  printf "\n\n>>> $1\n"
}

case $CONSOLE in
*plain*)
  CONFIG=../configs/c8-with-console.yaml
  ;;
*telemetry*)
  CONFIG=../configs/c8-with-console-and-telemetry.yaml
  ;;
*)
  log "Unknown config"
  exit 1
  ;;
esac

case $COMMAND in
install)
  log "Installing C8"
  ./c8-install.sh $CAMUNDA_LOCAL $CONFIG
  ;;
apply)
  log "Applying changes"
  ./c8-apply-changes.sh $CAMUNDA_LOCAL $CONFIG
  ;;
cleanup)
  log "Cleaning up C8"
  ./c8-cleanup.sh $CAMUNDA_LOCAL $CONFIG
  ;;
*)
  log "Unknown command"
  ;;
esac
