apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: camunda-platform
name: camunda-platform
repo: https://helm.camunda.io
# NOTE: We should use "nameTemplate" not "releaseName" to keep the names as same as using Helm CLI.
nameTemplate: camunda-platform
namespace: camunda-platform
IncludeCRDs: true
valuesMerge: merge
